# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiRulez < Formula
  desc "⚡ Lightning-fast CLI tool (written in Go) for managing AI assistant rules"
  homepage "https://github.com/Goldziher/ai-rulez"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v2.0.1/ai-rulez_2.0.1_darwin_amd64.tar.gz"
      sha256 "932e7f58cf5b7e5eb86ec678985d892a7108c790c58cc1757a5e0b7dec4baf51"

      def install
        bin.install "ai-rulez"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v2.0.1/ai-rulez_2.0.1_darwin_arm64.tar.gz"
      sha256 "e8d091d60366e802a4cea3c69ff2b5e1a7066eab9e9cea4a52c746c89a3829fd"

      def install
        bin.install "ai-rulez"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v2.0.1/ai-rulez_2.0.1_linux_amd64.tar.gz"
      sha256 "149faa3944c018ee5370e2a4a0b0fd1ce165d09670903180032823a982471fa1"
      def install
        bin.install "ai-rulez"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v2.0.1/ai-rulez_2.0.1_linux_arm64.tar.gz"
      sha256 "7fddf92dbc7d4a5bf527acea8a37bef60ed3da1d02be853cfd50323b090e14ea"
      def install
        bin.install "ai-rulez"
      end
    end
  end

  test do
    system "#{bin}/ai-rulez", "--version"
  end
end
