# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiRulez < Formula
  desc "⚡ Lightning-fast CLI tool (written in Go) for managing AI assistant rules"
  homepage "https://github.com/Goldziher/ai-rulez"
  version "1.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v1.4.3/ai-rulez_1.4.3_darwin_amd64.tar.gz"
      sha256 "b50563de1e32856aef693da382646ccd4a21ab181d5106798e5c706c88ed5615"

      def install
        bin.install "ai-rulez"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v1.4.3/ai-rulez_1.4.3_darwin_arm64.tar.gz"
      sha256 "04a4aae9f6530e34d24a8c14c15c18457a7bda0bdcc5c30232766aaf329d0dc3"

      def install
        bin.install "ai-rulez"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v1.4.3/ai-rulez_1.4.3_linux_amd64.tar.gz"
      sha256 "5bd4be7c5e6af38c211d22f17adcc2d64f9a9dd0202f0e8ebb2b7bf33e17abe7"
      def install
        bin.install "ai-rulez"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v1.4.3/ai-rulez_1.4.3_linux_arm64.tar.gz"
      sha256 "b6569e08ee122b96bb9ad386be96404756a702f872494c71b6c8ddb636d462f6"
      def install
        bin.install "ai-rulez"
      end
    end
  end

  test do
    system "#{bin}/ai-rulez", "--version"
  end
end
