# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiRulez < Formula
  desc "⚡ Lightning-fast CLI tool (written in Go) for managing AI assistant rules"
  homepage "https://github.com/Goldziher/ai-rulez"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v1.1.3/ai-rulez_1.1.3_darwin_amd64.tar.gz"
      sha256 "2e33468212491d19abf01bc7a573d1bb5ce9c263a63fab011ff69d326e175602"

      def install
        bin.install "ai-rulez"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v1.1.3/ai-rulez_1.1.3_darwin_arm64.tar.gz"
      sha256 "fa131a6feda502cb41bd2dca3a3795faa46186a998f47a3a861ee1c295ded49b"

      def install
        bin.install "ai-rulez"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v1.1.3/ai-rulez_1.1.3_linux_amd64.tar.gz"
      sha256 "8d275773ff463ec5f0ca1542e9d40f0bda8ea346c71ef04318f79b72cb3ffc4e"
      def install
        bin.install "ai-rulez"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v1.1.3/ai-rulez_1.1.3_linux_arm64.tar.gz"
      sha256 "0fb0a43643acb3ddfe753864029d32f4d1002f97be70ae837508831cea2c2f98"
      def install
        bin.install "ai-rulez"
      end
    end
  end

  test do
    system "#{bin}/ai-rulez", "--version"
  end
end
