# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-rulez" do
  name "ai-rulez"
  desc "⚡ Lightning-fast CLI tool (written in Go) for managing AI assistant rules"
  homepage "https://github.com/Goldziher/ai-rulez"
  version "2.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-rulez"

  on_macos do
    on_intel do
      url "https://github.com/Goldziher/ai-rulez/releases/download/v#{version}/ai-rulez_#{version}_darwin_amd64.tar.gz"
      sha256 "9388591513455113ca5fc51585f0f19601627119780960e0f925e5f5f9b2211c"
    end
    on_arm do
      url "https://github.com/Goldziher/ai-rulez/releases/download/v#{version}/ai-rulez_#{version}_darwin_arm64.tar.gz"
      sha256 "8b94a5508e0763d6760f52e0bc8976670160e18b662a837c89305f32ff9b810e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Goldziher/ai-rulez/releases/download/v#{version}/ai-rulez_#{version}_linux_amd64.tar.gz"
      sha256 "b0352154461ffa7f61bb28580ee39248bcf60937986a124cb52b98118cf2c78b"
    end
    on_arm do
      url "https://github.com/Goldziher/ai-rulez/releases/download/v#{version}/ai-rulez_#{version}_linux_arm64.tar.gz"
      sha256 "cc841c4560fb76930ebf909885152d228ce7cfc1e37ca977c84c9d30bffa080d"
    end
  end

  # No zap stanza required
end
