# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiRulez < Formula
  desc "⚡ Lightning-fast CLI tool (written in Go) for managing AI assistant rules"
  homepage "https://github.com/Goldziher/ai-rulez"
  version "3.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v3.11.0/ai-rulez_3.11.0_darwin_amd64.tar.gz"
      sha256 "85d1935736f57d10b4abaf78b18f3470a9017f6f4c30e2d8c639fc66d255b198"

      define_method(:install) do
        bin.install "ai-rulez"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v3.11.0/ai-rulez_3.11.0_darwin_arm64.tar.gz"
      sha256 "fba9fb0f218e472eb2be33b6e61b6a61aea20dc78c4bbf33bc30616b1ece3c22"

      define_method(:install) do
        bin.install "ai-rulez"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v3.11.0/ai-rulez_3.11.0_linux_amd64.tar.gz"
      sha256 "1f629974ef6f862e2fb53ffdc33c6e52b4c31311a91094cb240c9f33f003d57b"
      define_method(:install) do
        bin.install "ai-rulez"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/ai-rulez/releases/download/v3.11.0/ai-rulez_3.11.0_linux_arm64.tar.gz"
      sha256 "165df8d07b8d39280ac2ee3da1fab27b4be9f3cdb0015d6b36ffb7ff7c50503b"
      define_method(:install) do
        bin.install "ai-rulez"
      end
    end
  end
end
