# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Basemind < Formula
  desc "Full AI context layer over MCP — code-map, document RAG, memory, web, git"
  homepage "https://github.com/Goldziher/basemind"
  version "0.6.1"
  license "MIT"

  # Apple Silicon only — Intel macOS is not supported.
  on_macos do
    on_arm do
      url "https://github.com/Goldziher/basemind/releases/download/v0.6.1/basemind-aarch64-apple-darwin.tar.gz"
      sha256 "b5dcd9a1371a34da3b76a807b8e21763acff0ea32ae4e5cc08d56eda87d4295a"
    end
    on_intel do
      odie "basemind does not ship Intel macOS (x86_64) binaries; Apple Silicon (arm64) only"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/basemind/releases/download/v0.6.1/basemind-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "44644374068ee5c9f42380f6cf7f3c615546c40b6b11bda7225e95819c4040d9"
    end
    on_intel do
      url "https://github.com/Goldziher/basemind/releases/download/v0.6.1/basemind-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3aa5a91ca1a9a37f7d0a9a84d3d5ae8966da2218485bf141d25b8f842bc31eaa"
    end
  end

  def install
    # Archive root holds the binary + lib/ of bundled native libs; the binary's
    # rpath resolves lib/ relative to its own location, so keep them together in
    # libexec and expose the binary on PATH via a symlink.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"basemind"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/basemind --version")
  end
end
