# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Basemind < Formula
  desc "Full AI context layer over MCP — code-map, document RAG, memory, web, git"
  homepage "https://github.com/Goldziher/basemind"
  version "0.28.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/basemind/releases/download/v0.28.0/basemind-aarch64-apple-darwin.tar.gz"
      sha256 "420faad446d2712440df42fccb60ac05ee8523ea9eaf6a5a17a92e0a8fcd4b2a"
    end
    on_intel do
      url "https://github.com/Goldziher/basemind/releases/download/v0.28.0/basemind-x86_64-apple-darwin.tar.gz"
      sha256 "ab80423189bb2c6ae094e5ab620cd344610320863686e4d1a8f71ceeed26c5a2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/basemind/releases/download/v0.28.0/basemind-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c2e2000c3905eaf8ced7c1ff8707a903080c720e13367b0327bc8f43a62c8029"
    end
    on_intel do
      url "https://github.com/Goldziher/basemind/releases/download/v0.28.0/basemind-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1916727846e88fad80aee2af68141e63389fecca8f791c2c2defb95f81e6b5f1"
    end
  end

  def install
    # Archive root holds the binary + lib/ of bundled native libs (plus a co-located
    # libonnxruntime.dylib on Intel macOS); the binary's rpath resolves lib/ relative
    # to its own location and ort resolves the ONNX dylib relative to the executable,
    # so keep them together in libexec and expose the binary on PATH via a symlink.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"basemind"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/basemind --version")
  end
end
