# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Basemind < Formula
  desc "Full AI context layer over MCP — code-map, document RAG, memory, web, git"
  homepage "https://github.com/Goldziher/basemind"
  version "0.19.0"
  license "MIT"

  # Apple Silicon only — Intel macOS is not supported. Enforce this with a
  # depends_on arch requirement (evaluated at install time) rather than a
  # load-time odie, which would abort brew for every formula in the tap on an
  # Intel host the moment the tap is read.
  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/Goldziher/basemind/releases/download/v0.19.0/basemind-aarch64-apple-darwin.tar.gz"
      sha256 "abe92c2c6a1ce33b9a4184059dc562447ad95bf009028a4167d44d1cafcddbe9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/basemind/releases/download/v0.19.0/basemind-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3aef64f02565ec0bbe792035887cc751eaaea487fc4d47456d0597c700e5bd1b"
    end
    on_intel do
      url "https://github.com/Goldziher/basemind/releases/download/v0.19.0/basemind-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ff78eec1c2831b4f08fe7dfa6b4552f9fb34a5f2ceb7a6d13339b81fe98d615c"
    end
  end

  def install
    # Archive root holds the binary + lib/ of bundled native libs; the binary's
    # rpath resolves lib/ relative to its own location, so keep them together in
    # libexec and expose the binary on PATH via a symlink.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"basemind"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/basemind --version")
  end
end
