# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhActionsUpdater < Formula
  desc "Fast GitHub Actions reference scanner and updater"
  homepage "https://github.com/Goldziher/gh-actions-updater"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/gh-actions-updater/releases/download/v0.1.2/gh-actions-updater-x86_64-apple-darwin.tar.gz"
      sha256 "ad1a22a038e76fc7b5c881f3e49302dfb0709fc4af0056d23b9f5fa66e784129"

      define_method(:install) do
        bin.install "gau"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/gh-actions-updater/releases/download/v0.1.2/gh-actions-updater-aarch64-apple-darwin.tar.gz"
      sha256 "31cb7256be671acfa0eb500d337ebf1bdd6da9608857143a2af8e45b369b1b18"

      define_method(:install) do
        bin.install "gau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/gh-actions-updater/releases/download/v0.1.2/gh-actions-updater-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "96de50c4b9dcbd9d5d83999fa42f6acfcd4740cb7bc0b2ca5a7a51610e662d4c"
      define_method(:install) do
        bin.install "gau"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/gh-actions-updater/releases/download/v0.1.2/gh-actions-updater-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c77ebfe254ea56061e39da57c3bf48b2a039903934cbdf0603ef3341205f9cb7"
      define_method(:install) do
        bin.install "gau"
      end
    end
  end

  test do
    system "#{bin}/gau", "--version"
  end
end
