# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhActionsUpdater < Formula
  desc "Fast GitHub Actions reference scanner and updater"
  homepage "https://github.com/Goldziher/gh-actions-updater"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/gh-actions-updater/releases/download/v0.1.7/gh-actions-updater-x86_64-apple-darwin.tar.gz"
      sha256 "610b4f0ce7d6d96b234cade42ae26a7874f1701e72451330942bcebf8d638602"

      define_method(:install) do
        bin.install "gau"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/gh-actions-updater/releases/download/v0.1.7/gh-actions-updater-aarch64-apple-darwin.tar.gz"
      sha256 "3a0730d56772e14fc090afc072bc9aa982126c6241b0da63759002dec72cdfe5"

      define_method(:install) do
        bin.install "gau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/gh-actions-updater/releases/download/v0.1.7/gh-actions-updater-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d5834df166ab1b499ab94abb36d2eb92cf61d3efe45cc36f47cc36e845277f3e"
      define_method(:install) do
        bin.install "gau"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/gh-actions-updater/releases/download/v0.1.7/gh-actions-updater-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a688c16f52f0d216af96531a4b263336fe8efacd046f2b167f873b584eff55ae"
      define_method(:install) do
        bin.install "gau"
      end
    end
  end

  test do
    system "#{bin}/gau", "--version"
  end
end
