# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Poly < Formula
  desc "Universal zero-dependency linter and formatter"
  homepage "https://github.com/Goldziher/poly"
  version "0.15.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/poly/releases/download/v0.15.0/poly-0.15.0-aarch64-apple-darwin.tar.gz"
      sha256 "55921abe449c28e7cf857d8e09bcd83acd1380099be69d597934be424a6b4673"
    end
    on_intel do
      url "https://github.com/Goldziher/poly/releases/download/v0.15.0/poly-0.15.0-x86_64-apple-darwin.tar.gz"
      sha256 "3e93e9b0a5994b5aeb8182c4fd248f8b028c0dc127687e0ca354ac388f6c4520"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/poly/releases/download/v0.15.0/poly-0.15.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "481e8a59748b1409b9113fc21f7b51c05122b8522f7aa74445240fed70488edc"
    end
    on_intel do
      url "https://github.com/Goldziher/poly/releases/download/v0.15.0/poly-0.15.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "cfa972d24fe496d1b397b7786a0676150a2163954061a8c57031f210e98f1e65"
    end
  end

  def install
    bin.install "poly"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/poly --version")
  end
end
