# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Polylint < Formula
  desc "Universal zero-dependency linter and formatter"
  homepage "https://github.com/Goldziher/polylint"
  url "https://github.com/Goldziher/polylint/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "53abb4de9a1c3c723a67843c5fb4b2cf0d19167de7c92d00b2849f2e12859377"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/poly-cli")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/poly --version")
  end
end
