# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Poly < Formula
  desc "Universal zero-dependency linter and formatter"
  homepage "https://github.com/Goldziher/poly"
  version "0.10.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/poly/releases/download/v0.10.0/poly-0.10.0-aarch64-apple-darwin.tar.gz"
      sha256 "140da46e788250848506c53c23ba51f77b2ba3936dbb5803051b6c8d40cad9c6"
    end
    on_intel do
      url "https://github.com/Goldziher/poly/releases/download/v0.10.0/poly-0.10.0-x86_64-apple-darwin.tar.gz"
      sha256 "79495990a16c6526529944c4ba10802ea08893d479f4aa5f777c5e452532e508"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/poly/releases/download/v0.10.0/poly-0.10.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "407165cf955b3211bcc4650e12be431f40ca5a346739707df59899f71b88d0e6"
    end
    on_intel do
      url "https://github.com/Goldziher/poly/releases/download/v0.10.0/poly-0.10.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d0de92f56d2c304dadd943344d61fd06e190ed40e5532d7ee0b125a3adf02f53"
    end
  end

  def install
    bin.install "poly"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/poly --version")
  end
end
