# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scythe < Formula
  desc "Polyglot SQL-to-code generator with built-in linting and formatting"
  homepage "https://github.com/Goldziher/scythe"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/scythe/releases/download/v0.17.0/scythe-x86_64-apple-darwin.tar.gz"
      sha256 "55a99da5fc14a8d36a5aac3878669ad21e39513b2be769f72b27220b6548f962"

      define_method(:install) do
        bin.install "scythe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/scythe/releases/download/v0.17.0/scythe-aarch64-apple-darwin.tar.gz"
      sha256 "0cd41813cb9e63a46068f02b0d9373c2d45f301a432a1ca6f0bd6af88da32464"

      define_method(:install) do
        bin.install "scythe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/scythe/releases/download/v0.17.0/scythe-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6d15092c601f9c925186402eb7ed903fb781765270818eb2839b920a10375195"
      define_method(:install) do
        bin.install "scythe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/scythe/releases/download/v0.17.0/scythe-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "05682ba7f147f01134eacd2c964e2d63ebd2bcd0bd18593a53ef4cf290810481"
      define_method(:install) do
        bin.install "scythe"
      end
    end
  end

  test do
    system "#{bin}/scythe", "--version"
  end
end
