# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scythe < Formula
  desc "Polyglot SQL-to-code generator with built-in linting and formatting"
  homepage "https://github.com/Goldziher/scythe"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/scythe/releases/download/v0.10.0/scythe-x86_64-apple-darwin.tar.gz"
      sha256 "aec72ef0cad641d5e02fee16d8a6416c0b26ebbbe7c3c7ded9dbf1107fbb10a8"

      define_method(:install) do
        bin.install "scythe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/scythe/releases/download/v0.10.0/scythe-aarch64-apple-darwin.tar.gz"
      sha256 "aeda29eaa936db6ff68ed30b0c3799b6392fbda665ba2b498c05f0e987b86896"

      define_method(:install) do
        bin.install "scythe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/scythe/releases/download/v0.10.0/scythe-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "381a5a15c274d046de8ec1f077021181d5a05e080a58deacde365d687f29f1e0"
      define_method(:install) do
        bin.install "scythe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/scythe/releases/download/v0.10.0/scythe-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3f6ada5c0ba3e04604ae16e0b4a0470c73bf9c9d33667eccbfdb0b396a152c17"
      define_method(:install) do
        bin.install "scythe"
      end
    end
  end

  test do
    system "#{bin}/scythe", "--version"
  end
end
