# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scythe < Formula
  desc "Polyglot SQL-to-code generator with built-in linting and formatting"
  homepage "https://github.com/Goldziher/scythe"
  version "0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goldziher/scythe/releases/download/v0.6.4/scythe-x86_64-apple-darwin.tar.gz"
      sha256 "89d5df1ab1eb52d8fbbc510653a473687228a46ece8e407e5cfb2101cab1a2a6"

      define_method(:install) do
        bin.install "scythe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goldziher/scythe/releases/download/v0.6.4/scythe-aarch64-apple-darwin.tar.gz"
      sha256 "2f96b4c9cbe1891d05ab382644b463e5f42f70af572e45187689f45b19626f7a"

      define_method(:install) do
        bin.install "scythe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/scythe/releases/download/v0.6.4/scythe-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0b1bba59a0360f157071b3790e423b9c0ca56b01cb4dcdfcc914aae152185c09"
      define_method(:install) do
        bin.install "scythe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goldziher/scythe/releases/download/v0.6.4/scythe-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "63e3b68690a73c152a5c59bede5a0ac0a13c4b7d3e8d0b3314e855cbf537f4d0"
      define_method(:install) do
        bin.install "scythe"
      end
    end
  end

  test do
    system "#{bin}/scythe", "--version"
  end
end
