# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Starmetal < Formula
  desc "High-performance self-hosted package registry and registry proxy"
  homepage "https://github.com/Goldziher/starmetal"
  url "https://github.com/Goldziher/starmetal/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "1854284d97f98efc76b7122bfcc1b27a80473e18b70ca5b41a51bc6c10a7be76"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/starmetal-cli")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sm --version")
  end
end
