# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh; do not edit by hand.
class Starmetal < Formula
  desc "High-performance self-hosted package registry and registry proxy"
  homepage "https://github.com/Goldziher/starmetal"
  url "https://github.com/Goldziher/starmetal/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "f2755d0b5a758bb632f733159cc651cf2bd8083e5689f0e9291662f33608d27d"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/starmetal-cli")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sm --version")
  end
end
