# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Uncomment < Formula
  desc "A fast, accurate comment removal tool using tree-sitter for AST parsing"
  homepage "https://github.com/Goldziher/uncomment"
  version "3.10.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.10.0/uncomment-aarch64-apple-darwin.tar.gz"
      sha256 "4f066abf1fefe73a45b632838cbe7555d341ccafdb3134e45666174404b5e45f"
    end
    on_intel do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.10.0/uncomment-x86_64-apple-darwin.tar.gz"
      sha256 "cc617d3d6cafd0abc6d19d8195c66c3a0465d5b23374dbe9aa8c95ce7b557bf7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.10.0/uncomment-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8ea1940fd3e28956452dd37b9c06a8340beadf0af7fd0c5899fd6ee78eba720f"
    end
    on_intel do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.10.0/uncomment-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1be463472df0988e0499b3b45279d60755a04633d0699e8fa777b5948d968c6e"
    end
  end

  def install
    bin.install "uncomment"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uncomment --version")
  end
end
