# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Uncomment < Formula
  desc "A fast, accurate comment removal tool using tree-sitter for AST parsing"
  homepage "https://github.com/Goldziher/uncomment"
  version "3.5.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.5.2/uncomment-aarch64-apple-darwin.tar.gz"
      sha256 "65a8aefd5ba950df41aa6f06643ae5b43662c00278851bb66d3e6db81408ca4e"
    end
    on_intel do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.5.2/uncomment-x86_64-apple-darwin.tar.gz"
      sha256 "007be8a65bc4746f4097b6f7c18a3dab134a1042a124f5fb4808b9b768ea9777"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.5.2/uncomment-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a6ffb72b4acbae5d6565e9e6755fa03a8c86bd72342d171a3d10088e6fd340f2"
    end
    on_intel do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.5.2/uncomment-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "850eed7595ab6a84fa56523d389d15ef9ddf095301d67132fa43567705658b62"
    end
  end

  def install
    bin.install "uncomment"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uncomment --version")
  end
end
