# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Uncomment < Formula
  desc "A fast, accurate comment removal tool using tree-sitter for AST parsing"
  homepage "https://github.com/Goldziher/uncomment"
  version "3.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.1.0/uncomment-aarch64-apple-darwin.tar.gz"
      sha256 "92a1ec76087ada2914a6bd0810214d8fe240fe2e2252d17a5e43533d5fbf1793"
    end
    on_intel do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.1.0/uncomment-x86_64-apple-darwin.tar.gz"
      sha256 "443fec76921c837b984481a6646aa217c6a894ad7833606aeb450d00ec12ad9f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.1.0/uncomment-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2a54d9f7aa61e9be71da6b3cf809cf8e9e8977ba806fc5069373e1d961192ea4"
    end
    on_intel do
      url "https://github.com/Goldziher/uncomment/releases/download/v3.1.0/uncomment-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ba0cd01944b3ea9f089d981cae202e94d546181b889c0cc5103b2148f028c30c"
    end
  end

  def install
    bin.install "uncomment"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uncomment --version")
  end
end
