# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Voom < Formula
  desc "Fast, safe, parallel build-artifact pruning across every major language ecosystem"
  homepage "https://github.com/Goldziher/voom"
  version "0.4.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/voom/releases/download/v0.4.4/voom-aarch64-apple-darwin.tar.gz"
      sha256 "a29e16a772618582e44aec12bd80a8c0a802c4983ea1b0b0158c5aa453354db8"
    end
    on_intel do
      url "https://github.com/Goldziher/voom/releases/download/v0.4.4/voom-x86_64-apple-darwin.tar.gz"
      sha256 "d13422a8d84e5480c378996c0d2a4078355d8444e0c5b11ac7ec128081a3c2e2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/voom/releases/download/v0.4.4/voom-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3cacb716078e6c026652f03b135a9a3da4343a5e4b5bdf3a9f9f44314de564d3"
    end
    on_intel do
      url "https://github.com/Goldziher/voom/releases/download/v0.4.4/voom-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "05373a64230e746a23249824088b74ca0a8eeaa10f45def771707e6eac19afea"
    end
  end

  def install
    bin.install "voom"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/voom --version")
  end
end
