# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Voom < Formula
  desc "Fast, safe, parallel build-artifact pruning across every major language ecosystem"
  homepage "https://github.com/Goldziher/voom"
  version "0.6.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/voom/releases/download/v0.6.1/voom-aarch64-apple-darwin.tar.gz"
      sha256 "efa0ac7ad5635b41566fe2ca259b7c7de856e97dde5169fb78791a1fc8d8ce9e"
    end
    on_intel do
      url "https://github.com/Goldziher/voom/releases/download/v0.6.1/voom-x86_64-apple-darwin.tar.gz"
      sha256 "afb0a0b3a3e15d33aa6596f48c38551276b11fe3c298a24cb6f524007791425c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/voom/releases/download/v0.6.1/voom-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b5d89ed521e3e3201ff3a3a3e06fe5c6431dacbb1be93cc380210a73fc6bd9a5"
    end
    on_intel do
      url "https://github.com/Goldziher/voom/releases/download/v0.6.1/voom-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "904e6e8083c7c32dfab2b1dd7c195bf96e8dfe2764de5a2e4b16213d4a0cf6c6"
    end
  end

  def install
    bin.install "voom"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/voom --version")
  end
end
