# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Voom < Formula
  desc "Fast, safe, parallel build-artifact pruning across every major language ecosystem"
  homepage "https://github.com/Goldziher/voom"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Goldziher/voom/releases/download/v0.4.0/voom-aarch64-apple-darwin.tar.gz"
      sha256 "6bcbf557f1673d1bcb2b62579b6b42c65c5d10483720e28eff4f1d90fc3c0ea0"
    end
    on_intel do
      url "https://github.com/Goldziher/voom/releases/download/v0.4.0/voom-x86_64-apple-darwin.tar.gz"
      sha256 "750b43fd126d70450df42c11aa4ac5a15ab29e30a22054df19c7773ec9b64d2c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Goldziher/voom/releases/download/v0.4.0/voom-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b24e7c4a49e3d2e31ca1dc6c5b0cedae2dd8cc67747213b4fd0779679b8c064e"
    end
    on_intel do
      url "https://github.com/Goldziher/voom/releases/download/v0.4.0/voom-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fe47b690a70bec25e52b9ba6922e300199e865bafed5cce40037785298300762"
    end
  end

  def install
    bin.install "voom"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/voom --version")
  end
end
